const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Dictionary,
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Flash,
		C3.Behaviors.Pin,
		C3.Behaviors.Tween,
		C3.Plugins.TextBox,
		C3.Behaviors.Anchor,
		C3.Plugins.AJAX,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.SpeechRecognition,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.Clipboard,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.lowercase,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.TextBox.Cnds.IsVisible,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.SpeechRecognition.Acts.RequestSpeechRecognition,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.SpeechRecognition.Acts.StopSpeechRecognition,
		C3.Plugins.SpeechRecognition.Cnds.OnSpeechRecognitionResult,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.SpeechRecognition.Exps.InterimTranscript,
		C3.Plugins.SpeechRecognition.Cnds.OnSpeechRecognitionEnd,
		C3.Plugins.SpeechRecognition.Exps.FinalTranscript,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Clipboard.Acts.CopyText,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject
	];
};
self.C3_JsPropNameTable = [
	{BrainVoiceAnswer: 0},
	{BrainText: 0},
	{BrainTitle: 0},
	{BrainBinDict: 0},
	{BrainArray: 0},
	{DragDrop: 0},
	{Flash: 0},
	{Pin: 0},
	{Tween: 0},
	{BrainBack: 0},
	{BrainQuestion: 0},
	{BrainTest: 0},
	{BrainWiz: 0},
	{Anchor: 0},
	{Background: 0},
	{GoAwayBrain: 0},
	{name: 0},
	{type: 0},
	{lesson: 0},
	{RecycleBin: 0},
	{isClicked: 0},
	{GoButton2: 0},
	{Overlay: 0},
	{RecycleBinText: 0},
	{AJAX: 0},
	{Keyboard: 0},
	{Browser: 0},
	{TopTitle2: 0},
	{Mic: 0},
	{Mouse: 0},
	{SpeechRecognition: 0},
	{UserTranscript: 0},
	{TextBoxSmall: 0},
	{TypeInstead: 0},
	{TextBoxBig: 0},
	{Sprite2: 0},
	{ItemName: 0},
	{Touch: 0},
	{PointsBubble: 0},
	{PointsCounter: 0},
	{LocalStorage: 0},
	{YesButton: 0},
	{NoButton: 0},
	{Rotate: 0},
	{Confetti: 0},
	{Particles: 0},
	{ConfirmationQuestion: 0},
	{DoneButton: 0},
	{ItemInstructions: 0},
	{ExampleText: 0},
	{SpeakInstructions: 0},
	{Trophy: 0},
	{PointsText: 0},
	{BrainWiz2: 0},
	{TextBoxSideways: 0},
	{PointsMessage: 0},
	{HazardousButton: 0},
	{DonateButton: 0},
	{Sad: 0},
	{Text: 0},
	{PlanetFlipLogo: 0},
	{WasteWizardBanner: 0},
	{Congrats: 0},
	{ShareButton: 0},
	{Clipboard: 0},
	{ShareOverlay: 0},
	{CopyButton: 0},
	{CloseShareOverlay: 0},
	{Copied: 0},
	{BrainAnswer: 0},
	{CurrentUserItem: 0},
	{RecycleService: 0},
	{BrainNum: 0},
	{BrainLoaded: 0},
	{UserPoints: 0},
	{myitem: 0},
	{myfind: 0},
	{myi: 0},
	{myinstructions: 0},
	{mybin: 0}
];

self.InstanceType = {
	BrainVoiceAnswer: class extends self.ITextInstance {},
	BrainText: class extends self.ITextInstance {},
	BrainTitle: class extends self.ITextInstance {},
	BrainBinDict: class extends self.IDictionaryInstance {},
	BrainArray: class extends self.IArrayInstance {},
	BrainBack: class extends self.ISpriteInstance {},
	BrainQuestion: class extends self.ITextInstance {},
	BrainTest: class extends self.ITextInputInstance {},
	BrainWiz: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	GoAwayBrain: class extends self.ISpriteInstance {},
	RecycleBin: class extends self.ISpriteInstance {},
	GoButton2: class extends self.ISpriteInstance {},
	Overlay: class extends self.ISpriteInstance {},
	RecycleBinText: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	TopTitle2: class extends self.ISpriteInstance {},
	Mic: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	SpeechRecognition: class extends self.IInstance {},
	UserTranscript: class extends self.ITextInstance {},
	TextBoxSmall: class extends self.ISpriteInstance {},
	TypeInstead: class extends self.ITextInstance {},
	TextBoxBig: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	ItemName: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	PointsBubble: class extends self.ISpriteInstance {},
	PointsCounter: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	YesButton: class extends self.ISpriteInstance {},
	NoButton: class extends self.ISpriteInstance {},
	Confetti: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	ConfirmationQuestion: class extends self.ITextInstance {},
	DoneButton: class extends self.ISpriteInstance {},
	ItemInstructions: class extends self.ITextInstance {},
	ExampleText: class extends self.ITextInstance {},
	SpeakInstructions: class extends self.ITextInstance {},
	Trophy: class extends self.ISpriteInstance {},
	PointsText: class extends self.ITextInstance {},
	BrainWiz2: class extends self.ISpriteInstance {},
	TextBoxSideways: class extends self.ISpriteInstance {},
	PointsMessage: class extends self.ITextInstance {},
	HazardousButton: class extends self.ISpriteInstance {},
	DonateButton: class extends self.ISpriteInstance {},
	Sad: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	PlanetFlipLogo: class extends self.ISpriteInstance {},
	WasteWizardBanner: class extends self.ISpriteInstance {},
	Congrats: class extends self.ITextInstance {},
	ShareButton: class extends self.ISpriteInstance {},
	Clipboard: class extends self.IInstance {},
	ShareOverlay: class extends self.ISpriteInstance {},
	CopyButton: class extends self.ISpriteInstance {},
	CloseShareOverlay: class extends self.ISpriteInstance {},
	Copied: class extends self.ITextInstance {}
}